(function($){var Data={defaults:{width:'100%',size:'medium',themes:[],placeholder:'Select an item',removable:false,empty:false,search:false,ajax:false,data:{},scrollContainer:null},setup:function(opts){var defKeys=Object.keys(this.defaults);var optKeys=Object.keys(opts);var isOk=true;optKeys.forEach(function(k){if($.inArray(k,defKeys)===-1){console.error('selectMania | wrong setup settings');isOk=false;}});if(isOk){this.defaults=$.extend(true,{},Data.defaults,opts);}}};var Engine={internalSettings:function($originalSelect,settings){var thisEngine=this;settings.multiple=false;settings.values=[];settings.multiple=$originalSelect.is('[multiple]');settings.disabled=$originalSelect.is('[disabled]');$originalSelect.find('option:selected').each(function(){settings.values.push({value:this.value,text:this.text});});return settings;},getAttrSettings:function($originalSelect){var attrData={};var attrs=['width','size','placeholder','removable','empty','search','scrollContainer'];attrs.forEach(function(attr){if($originalSelect.is('[data-'+attr+']')){var elAttr=$originalSelect.attr('data-'+attr);if(elAttr==='true'||elAttr==='false'){elAttr=elAttr==='true';}
attrData[attr]=elAttr;}});return attrData;},initialize:function($originalSelect,userSettings){var thisEngine=this;var settings=$.extend(true,{},userSettings);var attrSettings=thisEngine.getAttrSettings($originalSelect);settings=$.extend(settings,attrSettings);if(settings.empty){$originalSelect.val('');}
settings=thisEngine.internalSettings($originalSelect,settings);if(thisEngine.controlSettings($originalSelect,settings)){var $builtSelect=Build.build($originalSelect,settings);$builtSelect.data('selectMania-originalSelect',$originalSelect);$originalSelect.data('selectMania-element',$builtSelect);if(settings.ajax!==false){thisEngine.initAjax($builtSelect,settings);}
thisEngine.updateClean($builtSelect);$originalSelect.addClass('select-mania-original');$builtSelect.insertBefore($originalSelect);$originalSelect.appendTo($builtSelect);Binds.bind($builtSelect);}},update:function($originalSelect){var thisEngine=this;$selectManiaEl=$originalSelect.data('selectMania-element');$valueList=$selectManiaEl.find('.select-mania-values').first();$itemList=$selectManiaEl.find('.select-mania-items').first();if($originalSelect.is('[disabled]')){$selectManiaEl.addClass('select-mania-disabled');}
else{$selectManiaEl.removeClass('select-mania-disabled');}
$selectManiaEl.find('.select-mania-value').remove();$itemList.empty();$originalSelect.find('option:selected').each(function(){if($(this).is(':selected')){$valueList.append(Build.buildValue({value:this.value,text:this.text}));}});$itemList.append(Build.buildItemList($originalSelect.children()));thisEngine.updateClean($selectManiaEl);Binds.bind($selectManiaEl);},destroy:function($originalSelect){$selectManiaEl=$originalSelect.data('selectMania-element');$originalSelect.insertAfter($selectManiaEl);$selectManiaEl.remove();$originalSelect.removeClass('select-mania-original');},openDropdown:function($dropdown){var thisEngine=this;var $selectManiaEl=$dropdown.closest('.select-mania');if($selectManiaEl.is('[data-selectMania-scrollContainer]')){var $scrollContainer=$($selectManiaEl.attr('data-selectMania-scrollContainer'));Engine.positionDropdown($dropdown);$dropdown.addClass('select-mania-absolute');$scrollContainer.off('scroll.selectMania').on('scroll.selectMania',function(){$scrollContainer.off('scroll.selectMania');Engine.closeDropdown($('.select-mania-dropdown.open'));});$(window).off('resize.selectMania').on('resize.selectMania',function(){Engine.positionDropdown($dropdown);});}
$dropdown.stop().addClass('open').slideDown(100);$dropdown.find('.select-mania-items').scrollTop(0);thisEngine.focusSearch($dropdown);$(document).off('keydown.selectMania').on('keydown.selectMania',Binds.keyboardControl);},closeDropdown:function($dropdown){var $selectManiaEl=$dropdown.data('selectMania-element');$(document).off('keydown.selectMania');$dropdown.find('.select-mania-item').removeClass('select-mania-hover');if($dropdown.hasClass('select-mania-absolute')){var $selectManiaInner=$dropdown.data('selectMania-element').find('.select-mania-inner').first();$dropdown.removeClass('open').hide().insertAfter($selectManiaInner);$(window).off('resize.selectMania');var $scrollContainer=$($selectManiaEl.attr('data-selectMania-scrollContainer'));if($scrollContainer.length>0){$scrollContainer.off('scroll.selectMania');}}
else{$dropdown.stop().removeClass('open').slideUp(100);}},positionDropdown:function($dropdown){var $selectManiaEl=$dropdown.data('selectMania-element');var $itemList=$dropdown.find('.select-mania-items');var itemListScroll=$itemList.scrollTop();var selectManiaElPos=$selectManiaEl.offset();var selectManiaElWidth=$selectManiaEl.outerWidth();var selectManiaElHeight=$selectManiaEl.outerHeight();$dropdown.appendTo('body').css({position:'absolute',top:selectManiaElPos.top+selectManiaElHeight,left:selectManiaElPos.left,width:selectManiaElWidth});$itemList.scrollTop(itemListScroll);},selectItem:function($item){var $dropdown=$item.closest('.select-mania-dropdown');var $selectManiaEl=$dropdown.data('selectMania-element');var $originalSelect=$selectManiaEl.data('selectMania-originalSelect');if(!$item.is('.select-mania-selected')){var itemVal=$item.attr('data-value');var $value=Build.buildValue({value:itemVal,text:$item.text()});if($selectManiaEl.is('.select-mania-multiple')){$selectManiaEl.find('.select-mania-values').append($value);Engine.addMultipleVal($originalSelect,itemVal);}
else{$dropdown.find('.select-mania-item').removeClass('select-mania-selected');$selectManiaEl.find('.select-mania-values .select-mania-value').remove();$selectManiaEl.find('.select-mania-values').append($value);$originalSelect.val(itemVal);}
$item.addClass('select-mania-selected');$originalSelect.trigger('change');}
if($dropdown.is('.select-mania-absolute')){Engine.positionDropdown($dropdown);}
if(!$selectManiaEl.is('.select-mania-multiple')){Engine.closeDropdown($dropdown);}
Engine.updateClean($selectManiaEl);Binds.bind($selectManiaEl);},focusSearch:function($dropdown){$dropdown.find('.select-mania-search-input').focus();},addMultipleVal:function($originalSelect,val){var originalVals=$originalSelect.val();if(!(originalVals instanceof Array)){originalVals=[];}
originalVals.push(val);$originalSelect.val(originalVals);},removeMultipleVal:function($originalSelect,val){var originalVals=$originalSelect.val();if(!(originalVals instanceof Array)){originalVals=[];}
originalVals.splice($.inArray(val,originalVals),1);$originalSelect.val(originalVals);},updateClean:function($selectManiaEl){var $originalSelect=$selectManiaEl.data('selectMania-originalSelect');if($originalSelect.val()!==null&&$originalSelect.val().length>0){$selectManiaEl.find('.select-mania-clear-icon').show();}
else{$selectManiaEl.find('.select-mania-clear-icon').hide();}},doSearch:function($selectManiaEl){var $dropdown=$selectManiaEl.data('selectMania-dropdown');var searchVal=$dropdown.find('.select-mania-search-input').first().val();searchVal=searchVal.toLowerCase().trim();if(searchVal===''){$dropdown.find('.select-mania-group, .select-mania-item').removeClass('select-mania-hidden');return;}
$dropdown.find('.select-mania-item').each(function(){if($(this).text().toLowerCase().indexOf(searchVal)!==-1){$(this).removeClass('select-mania-hidden');}
else{$(this).addClass('select-mania-hidden');}});$dropdown.find('.select-mania-group').each(function(){if($(this).find('.select-mania-item:not(.select-mania-hidden)').length>0){$(this).removeClass('select-mania-hidden');}
else{$(this).addClass('select-mania-hidden');}});},doSearchAjax:function($selectManiaEl){var thisEngine=this;var $dropdown=$selectManiaEl.data('selectMania-dropdown');var thisSearch=$dropdown.find('.select-mania-search-input').first().val();$selectManiaEl.data('selectMania-ajaxReady',false);$selectManiaEl.data('selectMania-ajaxPage',1);thisEngine.dropdownLoading($selectManiaEl);var thisAjaxFunction=$selectManiaEl.data('selectMania-ajaxFunction');var thisAjaxData=$selectManiaEl.data('selectMania-ajaxData');thisAjaxFunction(thisSearch,1,thisAjaxData,function(optHTML){thisEngine.dropdownLoading($selectManiaEl,true);Engine.replaceItems($selectManiaEl,optHTML);Binds.bind($selectManiaEl);thisEngine.initAjax($selectManiaEl);});},addItems:function($selectManiaEl,optionsHTML){var thisEngine=this;thisEngine.addOrReplaceItems($selectManiaEl,optionsHTML,false);},replaceItems:function($selectManiaEl,optionsHTML){var thisEngine=this;thisEngine.addOrReplaceItems($selectManiaEl,optionsHTML,true);},addOrReplaceItems:function($selectManiaEl,optionsHTML,replace){var thisEngine=this;var $dropdown=$selectManiaEl.data('selectMania-dropdown');var $originalSelect=$selectManiaEl.data('selectMania-originalSelect');var $itemsContainer=$dropdown.find('.select-mania-items');var $options=$(optionsHTML);var selectedVals=thisEngine.getVal($selectManiaEl);selectedVals.forEach(function(val){$options.filter(function(){return $(this).attr('value')===val.value&&$(this).text()===val.text;}).prop('selected',true);});$builtItems=Build.buildItemList($options);if(replace===true){$originalSelect.find('option').remove(':not(:checked)');$itemsContainer.empty();}
$itemsContainer.append($builtItems);$originalSelect.append($options);Binds.bind($selectManiaEl);},initAjax:function($selectManiaEl,settings){if(typeof settings==='object'){if(settings.hasOwnProperty('ajax')&&typeof settings.ajax==='function'){$selectManiaEl.data('selectMania-ajaxFunction',settings.ajax);}
if(settings.hasOwnProperty('data')&&typeof settings.data==='object'){$selectManiaEl.data('selectMania-ajaxData',settings.data);}}
$selectManiaEl.data('selectMania-ajaxPage',1);$selectManiaEl.data('selectMania-ajaxReady',true);$selectManiaEl.data('selectMania-ajaxScrollDone',false);},dropdownLoading:function($selectManiaEl,hide){var isHide=false;if(typeof hide!=='undefined'&&hide===true){isHide=true;}
$dropdownContainer=$selectManiaEl.find('.select-mania-items-container').first();$dropdownContainer.find('.icon-loading-container').remove();if(isHide!==true){var $loadingIcon=$('<div class="icon-loading-container"></div>');$loadingIcon.append('<i class="icon-loading"></i>');$dropdownContainer.append($loadingIcon);}},getVal:function($selectManiaEl){var valObjs=[];$selectManiaEl.find('.select-mania-value').each(function(){var thisText=$(this).find('.select-mania-value-text').first().text();valObjs.push({value:$(this).attr('data-value'),text:thisText});});return valObjs;},clear:function($selectManiaEl){var $dropdown=$selectManiaEl.data('selectMania-dropdown');$selectManiaEl.find('.select-mania-value').remove();$dropdown.find('.select-mania-item').removeClass('select-mania-selected');var $originalSelect=$selectManiaEl.data('selectMania-originalSelect');if($selectManiaEl.is('.select-mania-multiple')){$originalSelect.val([]);}
else{$originalSelect.val('');}},setVal:function($selectManiaEl,valObjs){var thisEngine=this;var $originalSelect=$selectManiaEl.data('selectMania-originalSelect');thisEngine.clear($selectManiaEl);if(valObjs.length>1&&!$selectManiaEl.is('.select-mania-multiple')){valObjs=valObjs.slice(0,1);}
valObjs.forEach(function(val){var valObj=$.extend({value:'',text:'',selected:true},val);thisEngine.setOneValSelectMania($selectManiaEl,valObj);thisEngine.setOneValOriginal($originalSelect,valObj);});thisEngine.updateClean($selectManiaEl);Binds.bind($selectManiaEl);},setOneValSelectMania:function($selectMania,valObj){var $value=Build.buildValue(valObj);$selectMania.find('.select-mania-values').append($value);var $searchItem=$selectMania.find('.select-mania-item[data-value="'+valObj.value+'"]').filter(function(){return $(this).text()===valObj.text;});if($searchItem.length>0){$searchItem.first().addClass('select-mania-selected');}},setOneValOriginal:function($originalSelect,valObj){var $searchOpt=$originalSelect.find('option[value="'+valObj.value+'"]').filter(function(){return $(this).text()===valObj.text;});if($searchOpt.length<1){var $option=Build.buildOption(valObj);$originalSelect.append($option);}
else{var $foundOption=$searchOpt.first();$foundOption[0].selected=true;}},controlTarget:function($target,controls){if($.inArray('isSelect',controls)!==-1&&!$target.is('select')){console.error('selectMania | invalid select element');console.log($target[0]);return false;}
if($.inArray('isInitialized',controls)!==-1&&!$target.hasClass('select-mania-original')){console.error('selectMania | select is not initialized');console.log($target[0]);return false;}
if($.inArray('notInitialized',controls)!==-1&&$target.hasClass('select-mania-original')){console.error('selectMania | ignore because already initialized');console.log($target[0]);return false;}
if($.inArray('isSingle',controls)!==-1&&$target.length>1){console.error('selectMania | check method can be called on single element only');console.log($target[0]);return false;}
return true;},controlSettings:function($target,settings){if(settings.ajax!==false&&typeof settings.ajax!=='function'){settings.ajax=false;console.error('selectMania | invalid ajax function');console.log($target[0]);console.log(settings);return false;}
if($.inArray(settings.size,['tiny','small','medium','large'])===-1){settings.size='medium';console.error('selectMania | invalid size');console.log($target[0]);console.log(settings);return false;}
if(settings.scrollContainer!==null&&$(settings.scrollContainer).length<1){settings.scrollContainer=null;console.error('selectMania | invalid scroll container');console.log($target[0]);console.log(settings);return false;}
return true;},controlValues:function($target,values){if(!(values instanceof Array)){console.error('selectMania | values parameter is not a valid array');console.log($target[0]);console.log(values);return false;}
return true;},navigateItem:function($dropdown,nextOrPrevious){var $selectManiaEl=$dropdown.closest('.select-mania');var $itemList=$dropdown.find('.select-mania-items');var validItemSelector='.select-mania-item:not(.select-mania-disabled):not(.select-mania-hidden)';if($selectManiaEl.hasClass('select-mania-multiple')){validItemSelector+=':not(.select-mania-selected)';}
var $validItems=$dropdown.find(validItemSelector);var $hoveredItem=$dropdown.find(validItemSelector+'.select-mania-hover');var $targetItem=$();if($hoveredItem.length>0){if(nextOrPrevious==='next'){$targetItem=$validItems.slice($validItems.index($hoveredItem)+1).first();}
else if(nextOrPrevious==='previous'){$targetItem=$validItems.slice(0,$validItems.index($hoveredItem)).last();}}
else{$targetItem=$validItems.first();}
if($targetItem.length>0){$dropdown.find('.select-mania-item').removeClass('select-mania-hover');$targetItem.addClass('select-mania-hover');var $targetItemPosition=$targetItem.position();var $targetItemHeight=$targetItem.outerHeight(true);var $itemListHeight=$itemList.height();var $itemListScrollTop=$itemList.scrollTop();if($targetItemPosition.top<0){$itemList.scrollTop($itemListScrollTop+$targetItemPosition.top);}
else if($targetItemPosition.top+$targetItemHeight>$itemListHeight){$itemList.scrollTop($itemListScrollTop+$targetItemPosition.top+$targetItemHeight-$itemListHeight);}}}};var Build={build:function($originalSelect,settings){var thisBuild=this;var sizeClass='select-mania-'+settings.size;var widthStyle='style="width:'+settings.width+';"';var $selectManiaEl=$('<div class="select-mania '+sizeClass+'" '+widthStyle+'></div>');if(settings.multiple){$selectManiaEl.addClass('select-mania-multiple');}
if(settings.disabled){$selectManiaEl.addClass('select-mania-disabled');}
if(settings.themes instanceof Array&&settings.themes.length>0){settings.themes.forEach(function(theme){$selectManiaEl.addClass('select-mania-theme-'+theme);});}
if(settings.ajax!==false){$selectManiaEl.addClass('select-mania-ajax');}
if(settings.scrollContainer!==null){$selectManiaEl.attr('data-selectMania-scrollContainer',settings.scrollContainer);}
var $innerElements=thisBuild.buildInner(settings);var $dropdown=thisBuild.buildDropdown($originalSelect,settings);$selectManiaEl.append($innerElements).append($dropdown);$selectManiaEl.data('selectMania-dropdown',$dropdown);$dropdown.data('selectMania-element',$selectManiaEl);return $selectManiaEl;},buildInner:function(settings){var thisBuild=this;var $inner=$('<div class="select-mania-inner"></div>');var $values=$('<div class="select-mania-values"></div>');var $placeholder=$('<div class="select-mania-placeholder">'+settings.placeholder+'</div>');$values.append($placeholder);settings.values.forEach(function(val){$values.append(thisBuild.buildValue(val));});$inner.append($values);var $clean=$('<div class="select-mania-clear"></div>');if(settings.removable||settings.multiple){$clean.append('<i class="select-mania-clear-icon icon-cross">');}
$inner.append($clean);$inner.append($('<div class="select-mania-arrow"><i class="select-mania-arrow-icon icon-arrow-down"></i></div>'));return $inner;},buildValue:function(valObj){var valHtml='<div class="select-mania-value" data-value="'+valObj.value+'">'+
'<div class="select-mania-value-text">'+valObj.text+'</div>'+
'<div class="select-mania-value-clear">'+
'<i class="select-mania-value-clear-icon icon-cross"></i>'+
'</div>'+
'</div>';return $(valHtml);},buildOption:function(valObj){var $opt=$('<option value="'+valObj.value+'">'+valObj.text+'</option>');$opt[0].selected=valObj.selected;return $opt;},buildDropdown:function($originalSelect,settings){var thisBuild=this;var sizeClass='select-mania-'+settings.size;var $dropdown=$('<div class="select-mania-dropdown '+sizeClass+'"></div>');if(settings.search){var $dropdownSearch=$('<div class="select-mania-dropdown-search"></div>');$dropdownSearch.append('<input class="select-mania-search-input" />');$dropdown.append($dropdownSearch);}
var $itemListContainer=$('<div class="select-mania-items-container"></div>');var $itemList=$('<div class="select-mania-items"></div>');$itemList.append(thisBuild.buildItemList($originalSelect.children()));$itemListContainer.append($itemList);$dropdown.append($itemListContainer);if(settings.themes instanceof Array&&settings.themes.length>0){settings.themes.forEach(function(theme){$dropdown.addClass('select-mania-theme-'+theme);});}
return $dropdown;},buildItemList:function($optList){var thisBuild=this;$itemList=$();$optList.each(function(){if($(this).is('optgroup')){$itemList=$itemList.add(thisBuild.buildItemGroup($(this)));}
else if($(this).is('option')){$itemList=$itemList.add(thisBuild.buildItem($(this)));}});return $itemList;},buildItemGroup:function($optgroupEl){var thisBuild=this;$group=$('<div class="select-mania-group"></div>');var $groupInner=$('<div class="select-mania-group-inner"></div>');var $groupTitle=$('<div class="select-mania-group-title"></div>');if($optgroupEl.is('[data-icon]')){$groupTitle.append('<div class="select-mania-group-icon"><i class="'+$optgroupEl.attr('data-icon')+'"></i></div>');}
$groupTitle.append('<div class="select-mania-group-text">'+$optgroupEl.attr('label')+'</div>');$group.append($groupTitle);var groupIsDisabled=$optgroupEl.is(':disabled');if(groupIsDisabled){$group.addClass('select-mania-disabled');}
$optgroupEl.find('option').each(function(){$groupInner.append(thisBuild.buildItem($(this),groupIsDisabled));});$group.append($groupInner);return $group;},buildItem:function($optionEl,forceDisabled){var optionEl=$optionEl[0];var $item=$('<div class="select-mania-item" data-value="'+optionEl.value+'"></div>');if($optionEl.is('[data-icon]')){$item.append('<div class="select-mania-item-icon"><i class="'+$optionEl.attr('data-icon')+'"></i></div>');}
$item.append('<div class="select-mania-item-text">'+optionEl.text+'</div>');if($optionEl.is(':disabled')||Tools.def(forceDisabled)===true){$item.addClass('select-mania-disabled');}
if($optionEl.is(':selected')){$item.addClass('select-mania-selected');}
return $item;}};var Binds={bind:function($selectManiaEl){var thisBinds=this;var $originalSelect=$selectManiaEl.data('selectMania-originalSelect');var $dropdown=$selectManiaEl.data('selectMania-dropdown');if(!$selectManiaEl.is('.select-mania-disabled')){$(document).off('click.selectMania').on('click.selectMania',thisBinds.documentClick);$originalSelect.off('focus.selectMania').on('focus.selectMania',thisBinds.focus);$originalSelect.off('blur.selectMania').on('blur.selectMania',thisBinds.blur);$selectManiaEl.find('.select-mania-clear-icon').off('click.selectMania').on('click.selectMania',thisBinds.clearValues);$selectManiaEl.find('.select-mania-value-clear-icon').off('click.selectMania').on('click.selectMania',thisBinds.clearValue);$selectManiaEl.find('.select-mania-inner').off('click.selectMania').on('click.selectMania',thisBinds.dropdownToggle);$dropdown.find('.select-mania-item:not(.select-mania-disabled)').off('mouseenter.selectMania').on('mouseenter.selectMania',thisBinds.hoverItem);$dropdown.find('.select-mania-item:not(.select-mania-disabled)').off('click.selectMania').on('click.selectMania',thisBinds.itemSelection);$dropdown.find('.select-mania-search-input').off('input.selectMania').on('input.selectMania',thisBinds.inputSearch);$dropdown.find('.select-mania-items').off('wheel.selectMania').on('wheel.selectMania',thisBinds.scrollControl);if($selectManiaEl.is('.select-mania-ajax')){$dropdown.find('.select-mania-items').off('scroll.selectMania').on('scroll.selectMania',thisBinds.scrollAjax);}}
else{$originalSelect.off('focus.selectMania');$originalSelect.off('blur.selectMania');$selectManiaEl.find('.select-mania-clear-icon').off('click.selectMania');$selectManiaEl.find('.select-mania-value-clear-icon').off('click.selectMania');$selectManiaEl.find('.select-mania-inner').off('click.selectMania');$dropdown.find('.select-mania-item:not(.select-mania-disabled)').off('mouseenter.selectMania');$dropdown.find('.select-mania-item:not(.select-mania-disabled)').off('click.selectMania');$dropdown.find('.select-mania-search-input').off('input.selectMania');$dropdown.find('.select-mania-items').off('wheel.selectMania');$dropdown.find('.select-mania-items').off('scroll.selectMania');}},dropdownToggle:function(e){e.stopPropagation();var $selectManiaEl=$(this).closest('.select-mania');var $dropdown=$selectManiaEl.data('selectMania-dropdown');if($dropdown.is('.open')){Engine.closeDropdown($dropdown);}
else{Engine.closeDropdown($('.select-mania-dropdown.open'));Engine.openDropdown($dropdown);}},documentClick:function(e){if($(e.target).closest('.select-mania-dropdown').length<1){Engine.closeDropdown($('.select-mania-dropdown.open'));}},clearValues:function(e){e.stopPropagation();var $selectManiaEl=$(this).closest('.select-mania');var $dropdown=$selectManiaEl.data('selectMania-dropdown');var $originalSelect=$selectManiaEl.data('selectMania-originalSelect');Engine.clear($selectManiaEl);if($dropdown.is('.select-mania-absolute')){Engine.positionDropdown($dropdown);}
$originalSelect.trigger('change');Engine.updateClean($selectManiaEl);},clearValue:function(e){e.stopPropagation();var $selectManiaEl=$(this).closest('.select-mania');var $dropdown=$selectManiaEl.data('selectMania-dropdown');var $value=$(this).closest('.select-mania-value');$dropdown.find('.select-mania-item[data-value="'+$value.attr('data-value')+'"]').removeClass('select-mania-selected');$value.remove();var $originalSelect=$selectManiaEl.data('selectMania-originalSelect');Engine.removeMultipleVal($originalSelect,$value.attr('data-value'));if($dropdown.is('.select-mania-absolute')){Engine.positionDropdown($dropdown);}
$originalSelect.trigger('change');Engine.updateClean($selectManiaEl);},itemSelection:function(){var $selectedItem=$(this);Engine.selectItem($selectedItem);},inputSearch:function(){var $input=$(this);$selectManiaEl=$input.closest('.select-mania-dropdown').data('selectMania-element');var thisTime=200;if($selectManiaEl.is('.select-mania-ajax')){thisTime=400;}
clearTimeout($input.data('selectMania-searchTimer'));$input.data('selectMania-searchTimer',setTimeout(function(){if($selectManiaEl.is('.select-mania-ajax')){Engine.doSearchAjax($selectManiaEl);}
else{Engine.doSearch($selectManiaEl);}},thisTime));},scrollAjax:function(e){var $itemList=$(this);var $dropdown=$itemList.closest('.select-mania-dropdown');var $selectManiaEl=$dropdown.data('selectMania-element');if($selectManiaEl.data('selectMania-ajaxScrollDone')!==true){if($itemList.scrollTop()>=$itemList[0].scrollHeight-$itemList.outerHeight()-12){if($selectManiaEl.data('selectMania-ajaxReady')===true){var thisPage=$selectManiaEl.data('selectMania-ajaxPage')+1;var thisSearch=$selectManiaEl.find('.select-mania-search-input').first().val();$selectManiaEl.data('selectMania-ajaxReady',false);$selectManiaEl.data('selectMania-ajaxPage',thisPage);Engine.dropdownLoading($selectManiaEl);var thisAjaxFunction=$selectManiaEl.data('selectMania-ajaxFunction');var thisAjaxData=$selectManiaEl.data('selectMania-ajaxData');thisAjaxFunction(thisSearch,thisPage,thisAjaxData,function(optHTML){Engine.dropdownLoading($selectManiaEl,true);if(optHTML.trim()!==''){Engine.addItems($selectManiaEl,optHTML);Binds.bind($selectManiaEl);$selectManiaEl.data('selectMania-ajaxReady',true);}
else{$selectManiaEl.data('selectMania-ajaxScrollDone',true);}});}}}},scrollControl:function(e){var $thisDropdown=$(this);if(e.originalEvent.deltaY<0){return($thisDropdown.scrollTop()>0);}
else{return($thisDropdown.scrollTop()+$thisDropdown.innerHeight()<$thisDropdown[0].scrollHeight);}},focus:function(e){var $originalSelect=$(this);var $selectManiaEl=$originalSelect.data('selectMania-element');$selectManiaEl.addClass('select-mania-focused');$originalSelect.off('keydown.selectMania').on('keydown.selectMania',Binds.keyboardOpening);},blur:function(e){var $originalSelect=$(this);var $selectManiaEl=$originalSelect.data('selectMania-element');$selectManiaEl.removeClass('select-mania-focused');$originalSelect.off('keydown.selectMania');},hoverItem:function(e){var $item=$(this);var $dropdown=$item.closest('.select-mania-dropdown');$dropdown.find('.select-mania-item').removeClass('select-mania-hover');$item.addClass('select-mania-hover');},keyboardOpening:function(e){var $originalSelect=$(this);var $selectManiaEl=$originalSelect.data('selectMania-element');var $dropdown=$selectManiaEl.data('selectMania-dropdown');var openingKeys=[13,32,37,38,39,40];if(!$dropdown.hasClass('open')&&$.inArray(e.keyCode,openingKeys)!==-1){e.preventDefault();e.stopPropagation();$originalSelect.blur();Engine.openDropdown($dropdown);}},keyboardControl:function(e){var $dropdown=$('.select-mania-dropdown.open').first();var controlKeys=[9,13,27,38,40];if($dropdown.length>0&&$.inArray(e.keyCode,controlKeys)!==-1){e.preventDefault();e.stopPropagation();switch(e.keyCode){case 13:var $hoverItem=$dropdown.find('.select-mania-item:not(.select-mania-disabled):not(.select-mania-hidden).select-mania-hover').first();if($hoverItem.length>0){Engine.selectItem($hoverItem);}
break;case 9:case 27:Engine.closeDropdown($dropdown);break;case 38:Engine.navigateItem($dropdown,'previous');break;case 40:Engine.navigateItem($dropdown,'next');break;}}}};var Tools={def:function(v){if(typeof v==='undefined'){return null;}
return v;}};var Methods={init:function(opts){var settings=$.extend(true,{},Data.defaults,opts);return this.each(function(){var $originalSelect=$(this);if(Engine.controlTarget($originalSelect,['isSelect','notInitialized'])){Engine.initialize($originalSelect,settings);}});},update:function(){return this.each(function(){var $originalSelect=$(this);if(Engine.controlTarget($originalSelect,['isInitialized'])){Engine.update($originalSelect);}});},destroy:function(){return this.each(function(){var $originalSelect=$(this);if(Engine.controlTarget($originalSelect,['isInitialized'])){Engine.destroy($originalSelect);}});},check:function(){if(Engine.controlTarget(this,['isSingle'])){return this.hasClass('select-mania-original');}},get:function(){if(Engine.controlTarget(this,['isSingle','isInitialized'])){var $selectManiaEl=this.data('selectMania-element');return Engine.getVal($selectManiaEl);}},set:function(values){if(Engine.controlTarget(this,['isSingle','isInitialized'])){if(Engine.controlValues(this,values)){var $selectManiaEl=this.data('selectMania-element');Engine.setVal($selectManiaEl,values);}}},clear:function(){return this.each(function(){var $originalSelect=$(this);if(Engine.controlTarget($originalSelect,['isInitialized'])){var $selectManiaEl=$originalSelect.data('selectMania-element');Engine.clear($selectManiaEl);$originalSelect.trigger('change');Engine.updateClean($selectManiaEl);}});},setup:function(){return this.each(function(){var $originalSelect=$(this);if(Engine.controlTarget($originalSelect,['isInitialized'])){var $selectManiaEl=$originalSelect.data('selectMania-element');Engine.clear($selectManiaEl);$originalSelect.trigger('change');Engine.updateClean($selectManiaEl);}});}};$.fn.selectMania=function(methodOrOpts){if(this.length<1){return;}
if(Methods[methodOrOpts]){var slicedArguments=Array.prototype.slice.call(arguments,1);return Methods[methodOrOpts].apply(this,slicedArguments);}
else if(typeof methodOrOpts==='object'||!methodOrOpts){return Methods.init.apply(this,arguments);}
else{console.error('selectMania | wrong method called');console.log(this);}};$.extend({selectManiaSetup:function(opts){Data.setup(opts);}});})(jQuery);